import { createContext, useContext, useState, useCallback } from 'react';

// ─── Translation dictionaries ─────────────────────────────────────────────────
const DICT = {
  ar: {
    // Auth
    'auth.login':             'تسجيل الدخول',
    'auth.logout':            'تسجيل الخروج',
    'auth.register':          'إنشاء حساب',
    'auth.identifier':        'البريد الإلكتروني أو رقم الهاتف',
    'auth.idPlaceholder':     'example@email.com أو 01XXXXXXXXX',
    'auth.password':          'كلمة المرور',
    'auth.confirm':           'تأكيد كلمة المرور',
    'auth.haveAccount':       'لديك حساب بالفعل؟',
    'auth.noAccount':         'ليس لديك حساب؟',
    'auth.showPwd':           'إظهار كلمة المرور',
    'auth.hidePwd':           'إخفاء كلمة المرور',

    // Login page
    'login.welcome':          'مرحباً بعودتك 👋',
    'login.subtitle':         'سجّل دخولك إلى حسابك في FarmFlow',
    'login.signing':          'جاري تسجيل الدخول…',
    'login.newHere':          'ليس لديك حساب؟',
    'login.buyerRole':        'مشترٍ',
    'login.sellerRole':       'بائع',
    'login.buyerDesc':        'تصفح وشراء الماشية',
    'login.sellerDesc':       'اعرض وبع حيواناتك',
    'login.getStarted':       'ابدأ الآن',
    'login.secure':           '🔒 جميع البيانات آمنة ومشفرة',
    'login.liveActivity':     'نشاط مباشر',
    'login.marketplace':      'السوق الموثوق لربط مربّي الماشية والمشترين في مصر',

    // Register page
    'reg.title':              'ابدأ الآن',
    'reg.marketplace':        'السوق الأول للماشية في مصر',
    'reg.chooseRole':         'اختر نوع حسابك',
    'reg.isBuyer':            'أنا مشترٍ',
    'reg.isSeller':           'أنا بائع',
    'reg.buyerCardDesc':      'ابحث عن الماشية المناسبة من مزارع موثوقة في جميع أنحاء مصر وتواصل مع البائعين مباشرة.',
    'reg.sellerCardDesc':     'أنشر إعلاناتك وتواصل مع المشترين في كل مصر. إدارة مزرعتك بالكامل من مكان واحد.',
    'reg.startBuyer':         'ابدأ الآن كمشترٍ',
    'reg.startSeller':        'ابدأ الآن كبائع',
    'reg.buyer':              'مشترٍ',
    'reg.seller':             'بائع / صاحب مزرعة',
    'reg.buyerTag':           'مشترٍ',
    'reg.sellerTag':          'بائع',
    'reg.secure':             'آمن ومحمي',
    'reg.verifiedSellers':    'بائعون موثقون',
    'reg.txProtection':       'حماية المعاملات',
    'reg.newMembers':         '٤٧ عضواً جديداً هذا الأسبوع',
    'reg.newMembersDesc':     'يمكنك الانضمام إلى مجتمع متنامٍ من المزارعين المصريين.',
    'reg.haveAccount':        'لديك حساب؟',
    'reg.changeRole':         'تغيير النوع',
    'reg.welcomeBuyer':       'ابحث عن الماشية المثالية',
    'reg.welcomeSeller':      'بع ماشيتك بكل سهولة',
    'reg.farmDetailsTitle':   'بيانات مزرعتك',
    'reg.farmDetailsDesc':    'أدخل بيانات مزرعتك لتظهر للمشترين بشكل احترافي. يمكنك تعديلها لاحقاً من الإعدادات.',
    'reg.buyerPanelDesc':     'تصفح آلاف الإعلانات المعتمدة من مزارع موثوقة في جميع أنحاء مصر.',
    'reg.sellerPanelDesc':    'وصل لمئات المشترين النشطين في كل مصر. أنشر إعلاناتك وأدر مزرعتك من مكان واحد.',
    'reg.step':               'الخطوة',
    'reg.of':                 'من',
    'reg.createAccount':      'أنشئ حسابك',
    'reg.farmInfo':           'بيانات المزرعة',
    'reg.step1':              'بيانات الحساب',
    'reg.step2':              'بيانات المزرعة',
    'reg.name':               'الاسم الكامل',
    'reg.namePlaceholder':    'محمد أحمد',
    'reg.email':              'البريد الإلكتروني',
    'reg.emailSub':           'البريد الإلكتروني',
    'reg.emailOptSub':        'البريد الإلكتروني (اختياري)',
    'reg.emailOptional':      'البريد الإلكتروني (اختياري)',
    'reg.phone':              'رقم الهاتف',
    'reg.personalPhone':      'رقم الهاتف الشخصي',
    'reg.farmPhone':          'رقم هاتف المزرعة',
    'reg.farmName':           'اسم المزرعة',
    'reg.farmNamePlaceholder':'مزرعة الأمل',
    'reg.governorate':        'المحافظة',
    'reg.govSelect':          'اختر المحافظة',
    'reg.experience':         'سنوات الخبرة',
    'reg.expSelect':          'اختر',
    'reg.expLt1':             'أقل من سنة',
    'reg.exp13':              '١–٣ سنوات',
    'reg.exp35':              '٣–٥ سنوات',
    'reg.exp510':             '٥–١٠ سنوات',
    'reg.expGt10':            'أكثر من ١٠ سنوات',
    'reg.animalTypes':        'أنواع الحيوانات',
    'reg.animalTypesTitle':   'أنواع الحيوانات التي تبيعها',
    'reg.animalTypesHint':    'اختر كل ما ينطبق',
    'reg.bio':                'نبذة عن المزرعة',
    'reg.bioPlaceholder':     'اكتب نبذة مختصرة عن مزرعتك وتخصصاتك…',
    'reg.nationalId':         'رقم الهوية الوطنية',
    'reg.nationalIdSub':      '١٤ رقمًا',
    'reg.nationalIdHint':     '14 رقمًا — يُستخدم للتحقق من هويتك',
    'reg.verifying':          'جاري التحقق من السجل المدني…',
    'reg.idValid':            '✅ رقم صحيح — تم التحقق',
    'reg.idInvalid':          '❌ رقم غير صحيح',
    'reg.idAlreadyReg':       'الرقم مسجل مسبقاً',
    'reg.idGenderMale':       'ذكر',
    'reg.idGenderFemale':     'أنثى',
    'reg.idYears':            'سنة',
    'reg.idErr.notFourteen':  'يجب أن يتكون من 14 رقمًا بالضبط',
    'reg.idErr.badCentury':   'الرقم الأول يجب أن يكون 2 أو 3',
    'reg.idErr.badMonth':     'شهر الميلاد غير صحيح',
    'reg.idErr.badDay':       'يوم الميلاد غير صحيح',
    'reg.idErr.futureDate':   'تاريخ الميلاد في المستقبل',
    'reg.idErr.tooYoung':     'يجب أن يكون العمر 16 عامًا على الأقل',
    'reg.idErr.badGov':       'كود المحافظة غير صحيح',
    'reg.pwdLabel':           'كلمة المرور',
    'reg.pwdHint':            '٨ أحرف كحد أدنى',
    'reg.pwdMin':             '⚠️ يجب ٨ أحرف على الأقل',
    'reg.pwdMatch':           '✓ كلمات المرور متطابقة',
    'reg.pwdNoMatch':         '✗ كلمات المرور غير متطابقة',
    'reg.termsAgree':         'أوافق على',
    'reg.termsService':       'شروط الخدمة',
    'reg.termsAnd':           'و',
    'reg.privacyPolicy':      'سياسة الخصوصية',
    'reg.terms':              'أوافق على شروط الخدمة وسياسة الخصوصية',
    'reg.next':               'التالي',
    'reg.nextFarm':           'التالي: بيانات المزرعة',
    'reg.back':               'رجوع',
    'reg.createFarm':         'إنشاء حساب المزرعة',
    'reg.submit.buyer':       'إنشاء الحساب',
    'reg.submit.seller':      'إنشاء حساب المزرعة',
    'reg.creating':           'جاري الإنشاء…',
    'reg.err.name':           'الاسم مطلوب',
    'reg.err.email':          'بريد إلكتروني غير صالح',
    'reg.err.emailFmt':       'صيغة البريد الإلكتروني غير صحيحة',
    'reg.err.phone':          'رقم الهاتف مطلوب',
    'reg.err.personalPhone':  'رقم الهاتف الشخصي مطلوب',
    'reg.err.nationalId':     'يجب التحقق من رقم الهوية الوطنية أولاً',
    'reg.err.pwdLen':         'كلمة المرور يجب أن تكون ٨ أحرف على الأقل',
    'reg.err.pwdMatch':       'كلمات المرور غير متطابقة',
    'reg.err.gov':            'اختر المحافظة',
    'reg.err.terms':          'يجب الموافقة على شروط الخدمة',
    'reg.err.farmName':       'اسم المزرعة مطلوب',
    'reg.err.farmPhone':      'رقم هاتف المزرعة مطلوب',

    // Nav
    'nav.dashboard':          'الرئيسية',
    'nav.listings':           'إعلاناتي',
    'nav.addListing':         'إضافة إعلان',
    'nav.expenses':           'المصروفات',
    'nav.income':             'الدخل',
    'nav.orders':             'الطلبات',
    'nav.settings':           'الإعدادات',
    'nav.browse':             'تصفح المزارع',
    'nav.farms':              'المزارع',

    // Common
    'common.save':            'حفظ',
    'common.cancel':          'إلغاء',
    'common.delete':          'حذف',
    'common.edit':            'تعديل',
    'common.close':           'إغلاق',
    'common.loading':         'جاري التحميل…',
    'common.optional':        '(اختياري)',
    'common.required':        'مطلوب',
    'common.search':          'بحث',
    'common.filter':          'تصفية',
    'common.all':             'الكل',
    'common.egp':             'ج.م',
    'common.kg':              'كجم',
    'common.networkErr':      'خطأ في الشبكة، حاول مجدداً',
    'common.unknownErr':      'حدث خطأ ما',
  },

  en: {
    // Auth
    'auth.login':             'Sign In',
    'auth.logout':            'Sign Out',
    'auth.register':          'Create Account',
    'auth.identifier':        'Email or Phone Number',
    'auth.idPlaceholder':     'example@email.com or 01XXXXXXXXX',
    'auth.password':          'Password',
    'auth.confirm':           'Confirm Password',
    'auth.haveAccount':       'Already have an account?',
    'auth.noAccount':         "Don't have an account?",
    'auth.showPwd':           'Show password',
    'auth.hidePwd':           'Hide password',

    // Login page
    'login.welcome':          'Welcome back 👋',
    'login.subtitle':         'Sign in to your FarmFlow account',
    'login.signing':          'Signing in…',
    'login.newHere':          'New to FarmFlow?',
    'login.buyerRole':        'Buyer',
    'login.sellerRole':       'Seller',
    'login.buyerDesc':        'Browse & buy livestock',
    'login.sellerDesc':       'List & sell your animals',
    'login.getStarted':       'Get Started',
    'login.secure':           '🔒 All data is encrypted and secure.',
    'login.liveActivity':     'Live Activity',
    'login.marketplace':      'The trusted marketplace for livestock across Egypt.',

    // Register page
    'reg.title':              'Get Started',
    'reg.marketplace':        "Egypt's #1 livestock marketplace",
    'reg.chooseRole':         'Choose your account type',
    'reg.isBuyer':            "I'm a Buyer",
    'reg.isSeller':           "I'm a Seller",
    'reg.buyerCardDesc':      'Browse thousands of verified livestock listings from trusted farms across Egypt.',
    'reg.sellerCardDesc':     'Post listings and connect with buyers across Egypt. Manage your entire farm from one place.',
    'reg.startBuyer':         'Get Started as Buyer →',
    'reg.startSeller':        'Get Started as Seller →',
    'reg.buyer':              'Buyer',
    'reg.seller':             'Seller / Farm Owner',
    'reg.buyerTag':           'Buyer',
    'reg.sellerTag':          'Seller',
    'reg.secure':             'Secure',
    'reg.verifiedSellers':    'Verified Sellers',
    'reg.txProtection':       'Transaction Protection',
    'reg.newMembers':         '47 new members this week',
    'reg.newMembersDesc':     'Join a growing community of Egyptian farmers.',
    'reg.haveAccount':        'Already have an account?',
    'reg.changeRole':         'Change role',
    'reg.welcomeBuyer':       'Find your perfect livestock',
    'reg.welcomeSeller':      'Sell your livestock easily',
    'reg.farmDetailsTitle':   'Farm Details',
    'reg.farmDetailsDesc':    'Enter your farm details to appear professionally to buyers. You can edit them later in settings.',
    'reg.buyerPanelDesc':     'Browse thousands of verified listings from trusted farms across Egypt.',
    'reg.sellerPanelDesc':    'Reach hundreds of active buyers across Egypt. Post listings and manage your farm in one place.',
    'reg.step':               'Step',
    'reg.of':                 'of',
    'reg.createAccount':      'Create your account',
    'reg.farmInfo':           'Farm Details',
    'reg.step1':              'Account Details',
    'reg.step2':              'Farm Details',
    'reg.name':               'Full Name',
    'reg.namePlaceholder':    'Mohamed Ahmed',
    'reg.email':              'Email Address',
    'reg.emailSub':           'Email Address',
    'reg.emailOptSub':        'Email Address (optional)',
    'reg.emailOptional':      'Email Address (optional)',
    'reg.phone':              'Phone Number',
    'reg.personalPhone':      'Personal Phone',
    'reg.farmPhone':          'Farm Phone',
    'reg.farmName':           'Farm Name',
    'reg.farmNamePlaceholder':'Al-Amal Farm',
    'reg.governorate':        'Governorate',
    'reg.govSelect':          'Select governorate',
    'reg.experience':         'Years of Experience',
    'reg.expSelect':          'Select',
    'reg.expLt1':             'Less than 1 year',
    'reg.exp13':              '1–3 years',
    'reg.exp35':              '3–5 years',
    'reg.exp510':             '5–10 years',
    'reg.expGt10':            '10+ years',
    'reg.animalTypes':        'Livestock Types',
    'reg.animalTypesTitle':   'Livestock you sell',
    'reg.animalTypesHint':    'Select all that apply',
    'reg.bio':                'About Your Farm',
    'reg.bioPlaceholder':     'Brief description of your farm and specialties…',
    'reg.nationalId':         'National ID',
    'reg.nationalIdSub':      '14 digits',
    'reg.nationalIdHint':     '14 digits — used to verify your identity',
    'reg.verifying':          'Verifying with Civil Registry…',
    'reg.idValid':            '✅ ID verified',
    'reg.idInvalid':          '❌ Invalid ID',
    'reg.idAlreadyReg':       'ID already registered',
    'reg.idGenderMale':       'Male',
    'reg.idGenderFemale':     'Female',
    'reg.idYears':            'yrs',
    'reg.idErr.notFourteen':  'Must be exactly 14 digits',
    'reg.idErr.badCentury':   'First digit must be 2 or 3',
    'reg.idErr.badMonth':     'Invalid birth month',
    'reg.idErr.badDay':       'Invalid birth day',
    'reg.idErr.futureDate':   'Birth date is in the future',
    'reg.idErr.tooYoung':     'Must be at least 16 years old',
    'reg.idErr.badGov':       'Invalid governorate code',
    'reg.pwdLabel':           'Password',
    'reg.pwdHint':            'min. 8 characters',
    'reg.pwdMin':             '⚠️ At least 8 characters',
    'reg.pwdMatch':           '✓ Passwords match',
    'reg.pwdNoMatch':         '✗ Passwords do not match',
    'reg.termsAgree':         'I agree to the',
    'reg.termsService':       'Terms of Service',
    'reg.termsAnd':           'and',
    'reg.privacyPolicy':      'Privacy Policy',
    'reg.terms':              'I agree to the Terms of Service & Privacy Policy',
    'reg.next':               'Next',
    'reg.nextFarm':           'Next: Farm Details',
    'reg.back':               'Back',
    'reg.createFarm':         'Create Farm Account',
    'reg.submit.buyer':       'Create Account',
    'reg.submit.seller':      'Create Farm Account',
    'reg.creating':           'Creating…',
    'reg.err.name':           'Name is required',
    'reg.err.email':          'Invalid email',
    'reg.err.emailFmt':       'Invalid email format',
    'reg.err.phone':          'Phone is required',
    'reg.err.personalPhone':  'Personal phone is required',
    'reg.err.nationalId':     'Please verify your National ID first',
    'reg.err.pwdLen':         'Password must be at least 8 characters',
    'reg.err.pwdMatch':       'Passwords do not match',
    'reg.err.gov':            'Please select a governorate',
    'reg.err.terms':          'Please accept the terms',
    'reg.err.farmName':       'Farm name is required',
    'reg.err.farmPhone':      'Farm phone is required',

    // Nav
    'nav.dashboard':          'Dashboard',
    'nav.listings':           'My Listings',
    'nav.addListing':         'Add Listing',
    'nav.expenses':           'Expenses',
    'nav.income':             'Income',
    'nav.orders':             'Orders',
    'nav.settings':           'Settings',
    'nav.browse':             'Browse Farms',
    'nav.farms':              'Farms',

    // Common
    'common.save':            'Save',
    'common.cancel':          'Cancel',
    'common.delete':          'Delete',
    'common.edit':            'Edit',
    'common.close':           'Close',
    'common.loading':         'Loading…',
    'common.optional':        '(optional)',
    'common.required':        'Required',
    'common.search':          'Search',
    'common.filter':          'Filter',
    'common.all':             'All',
    'common.egp':             'EGP',
    'common.kg':              'kg',
    'common.networkErr':      'Network error, please retry.',
    'common.unknownErr':      'Something went wrong.',
  },
};

// ─── Context ──────────────────────────────────────────────────────────────────
const LangContext = createContext({
  lang:    'ar',
  isRTL:   true,
  t:       (k) => k,
  setLang: () => {},
});

export const LangProvider = ({ children }) => {
  const stored = typeof localStorage !== 'undefined'
    ? (localStorage.getItem('farmflow_lang') || 'ar')
    : 'ar';

  const [lang, setLangState] = useState(stored);

  const setLang = useCallback((l) => {
    localStorage.setItem('farmflow_lang', l);
    setLangState(l);
  }, []);

  const t = useCallback(
    (key) => DICT[lang]?.[key] ?? DICT['ar']?.[key] ?? key,
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, isRTL: lang === 'ar', t, setLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);

// ─── Language toggle ──────────────────────────────────────────────────────────
export const LangToggle = ({ style = {}, dark = true }) => {
  const { lang, setLang } = useLang();
  return (
    <button
      type="button"
      onClick={() => setLang(lang === 'ar' ? 'en' : 'ar')}
      style={{
        display:       'inline-flex',
        alignItems:    'center',
        gap:           '5px',
        padding:       '6px 14px',
        borderRadius:  '20px',
        border:        dark ? '1.5px solid rgba(255,255,255,0.25)' : '1.5px solid #C8DCC9',
        background:    dark ? 'rgba(255,255,255,0.1)'              : '#F0F7F1',
        color:         dark ? 'rgba(255,255,255,0.9)'              : '#2D6235',
        fontSize:      '12px',
        fontWeight:    '700',
        cursor:        'pointer',
        letterSpacing: '0.3px',
        fontFamily:    'inherit',
        transition:    'all 0.15s',
        flexShrink:    0,
        ...style,
      }}
    >
      {lang === 'ar' ? '🌐 English' : '🌐 العربية'}
    </button>
  );
};
